// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptp_and_brdcst_msg.proto

#include "ptp_and_brdcst_msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR BroadcastTransformShare::BroadcastTransformShare(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.a_aa_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.alpha_ba_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.b_ab_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.alpha_bb_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.c_ac_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.alpha_bc_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BroadcastTransformShareDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastTransformShareDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastTransformShareDefaultTypeInternal() {}
  union {
    BroadcastTransformShare _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastTransformShareDefaultTypeInternal _BroadcastTransformShare_default_instance_;
PROTOBUF_CONSTEXPR TransformedShare::TransformedShare(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.share_a_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.share_b_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.share_c_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.associated_c_a_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.associated_c_b_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.associated_c_c_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TransformedShareDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransformedShareDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransformedShareDefaultTypeInternal() {}
  union {
    TransformedShare _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransformedShareDefaultTypeInternal _TransformedShare_default_instance_;
PROTOBUF_CONSTEXPR TransformedShareMsg::TransformedShareMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.transformedshare_)*/{}
  , /*decltype(_impl_.coeff_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TransformedShareMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransformedShareMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransformedShareMsgDefaultTypeInternal() {}
  union {
    TransformedShareMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransformedShareMsgDefaultTypeInternal _TransformedShareMsg_default_instance_;
PROTOBUF_CONSTEXPR BroadcastTransformShareMsg::BroadcastTransformShareMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.broadcast_)*/{}
  , /*decltype(_impl_.coeff_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BroadcastTransformShareMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastTransformShareMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastTransformShareMsgDefaultTypeInternal() {}
  union {
    BroadcastTransformShareMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastTransformShareMsgDefaultTypeInternal _BroadcastTransformShareMsg_default_instance_;
static ::_pb::Metadata file_level_metadata_ptp_5fand_5fbrdcst_5fmsg_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ptp_5fand_5fbrdcst_5fmsg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ptp_5fand_5fbrdcst_5fmsg_2eproto = nullptr;

const uint32_t TableStruct_ptp_5fand_5fbrdcst_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShare, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShare, _impl_.a_aa_),
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShare, _impl_.alpha_ba_),
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShare, _impl_.b_ab_),
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShare, _impl_.alpha_bb_),
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShare, _impl_.c_ac_),
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShare, _impl_.alpha_bc_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TransformedShare, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TransformedShare, _impl_.share_a_),
  PROTOBUF_FIELD_OFFSET(::TransformedShare, _impl_.share_b_),
  PROTOBUF_FIELD_OFFSET(::TransformedShare, _impl_.share_c_),
  PROTOBUF_FIELD_OFFSET(::TransformedShare, _impl_.associated_c_a_),
  PROTOBUF_FIELD_OFFSET(::TransformedShare, _impl_.associated_c_b_),
  PROTOBUF_FIELD_OFFSET(::TransformedShare, _impl_.associated_c_c_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TransformedShareMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TransformedShareMsg, _impl_.coeff_),
  PROTOBUF_FIELD_OFFSET(::TransformedShareMsg, _impl_.transformedshare_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareMsg, _impl_.broadcast_),
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareMsg, _impl_.coeff_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::BroadcastTransformShare)},
  { 12, -1, -1, sizeof(::TransformedShare)},
  { 24, -1, -1, sizeof(::TransformedShareMsg)},
  { 32, -1, -1, sizeof(::BroadcastTransformShareMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_BroadcastTransformShare_default_instance_._instance,
  &::_TransformedShare_default_instance_._instance,
  &::_TransformedShareMsg_default_instance_._instance,
  &::_BroadcastTransformShareMsg_default_instance_._instance,
};

const char descriptor_table_protodef_ptp_5fand_5fbrdcst_5fmsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030ptp_and_brdcst_msg.proto\"y\n\027BroadcastT"
  "ransformShare\022\014\n\004a_aa\030\001 \001(\t\022\020\n\010alpha_ba\030"
  "\002 \001(\t\022\014\n\004b_ab\030\003 \001(\t\022\020\n\010alpha_bb\030\004 \001(\t\022\014\n"
  "\004c_ac\030\005 \001(\t\022\020\n\010alpha_bc\030\006 \001(\t\"\215\001\n\020Transf"
  "ormedShare\022\017\n\007share_a\030\001 \001(\t\022\017\n\007share_b\030\002"
  " \001(\t\022\017\n\007share_c\030\003 \001(\t\022\026\n\016associated_c_a\030"
  "\004 \001(\t\022\026\n\016associated_c_b\030\005 \001(\t\022\026\n\016associa"
  "ted_c_c\030\006 \001(\t\"Q\n\023TransformedShareMsg\022\r\n\005"
  "coeff\030\001 \001(\005\022+\n\020transformedShare\030\002 \003(\0132\021."
  "TransformedShare\"X\n\032BroadcastTransformSh"
  "areMsg\022+\n\tbroadcast\030\001 \003(\0132\030.BroadcastTra"
  "nsformShare\022\r\n\005coeff\030\002 \001(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto = {
    false, false, 474, descriptor_table_protodef_ptp_5fand_5fbrdcst_5fmsg_2eproto,
    "ptp_and_brdcst_msg.proto",
    &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_ptp_5fand_5fbrdcst_5fmsg_2eproto::offsets,
    file_level_metadata_ptp_5fand_5fbrdcst_5fmsg_2eproto, file_level_enum_descriptors_ptp_5fand_5fbrdcst_5fmsg_2eproto,
    file_level_service_descriptors_ptp_5fand_5fbrdcst_5fmsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_getter() {
  return &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ptp_5fand_5fbrdcst_5fmsg_2eproto(&descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto);

// ===================================================================

class BroadcastTransformShare::_Internal {
 public:
};

BroadcastTransformShare::BroadcastTransformShare(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:BroadcastTransformShare)
}
BroadcastTransformShare::BroadcastTransformShare(const BroadcastTransformShare& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BroadcastTransformShare* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.a_aa_){}
    , decltype(_impl_.alpha_ba_){}
    , decltype(_impl_.b_ab_){}
    , decltype(_impl_.alpha_bb_){}
    , decltype(_impl_.c_ac_){}
    , decltype(_impl_.alpha_bc_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.a_aa_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_aa_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_a_aa().empty()) {
    _this->_impl_.a_aa_.Set(from._internal_a_aa(), 
      _this->GetArenaForAllocation());
  }
  _impl_.alpha_ba_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alpha_ba_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_alpha_ba().empty()) {
    _this->_impl_.alpha_ba_.Set(from._internal_alpha_ba(), 
      _this->GetArenaForAllocation());
  }
  _impl_.b_ab_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.b_ab_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_b_ab().empty()) {
    _this->_impl_.b_ab_.Set(from._internal_b_ab(), 
      _this->GetArenaForAllocation());
  }
  _impl_.alpha_bb_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alpha_bb_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_alpha_bb().empty()) {
    _this->_impl_.alpha_bb_.Set(from._internal_alpha_bb(), 
      _this->GetArenaForAllocation());
  }
  _impl_.c_ac_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.c_ac_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_c_ac().empty()) {
    _this->_impl_.c_ac_.Set(from._internal_c_ac(), 
      _this->GetArenaForAllocation());
  }
  _impl_.alpha_bc_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alpha_bc_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_alpha_bc().empty()) {
    _this->_impl_.alpha_bc_.Set(from._internal_alpha_bc(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:BroadcastTransformShare)
}

inline void BroadcastTransformShare::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.a_aa_){}
    , decltype(_impl_.alpha_ba_){}
    , decltype(_impl_.b_ab_){}
    , decltype(_impl_.alpha_bb_){}
    , decltype(_impl_.c_ac_){}
    , decltype(_impl_.alpha_bc_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.a_aa_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.a_aa_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.alpha_ba_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alpha_ba_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.b_ab_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.b_ab_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.alpha_bb_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alpha_bb_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.c_ac_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.c_ac_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.alpha_bc_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alpha_bc_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BroadcastTransformShare::~BroadcastTransformShare() {
  // @@protoc_insertion_point(destructor:BroadcastTransformShare)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BroadcastTransformShare::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.a_aa_.Destroy();
  _impl_.alpha_ba_.Destroy();
  _impl_.b_ab_.Destroy();
  _impl_.alpha_bb_.Destroy();
  _impl_.c_ac_.Destroy();
  _impl_.alpha_bc_.Destroy();
}

void BroadcastTransformShare::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BroadcastTransformShare::Clear() {
// @@protoc_insertion_point(message_clear_start:BroadcastTransformShare)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.a_aa_.ClearToEmpty();
  _impl_.alpha_ba_.ClearToEmpty();
  _impl_.b_ab_.ClearToEmpty();
  _impl_.alpha_bb_.ClearToEmpty();
  _impl_.c_ac_.ClearToEmpty();
  _impl_.alpha_bc_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BroadcastTransformShare::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string a_aa = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_a_aa();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "BroadcastTransformShare.a_aa"));
        } else
          goto handle_unusual;
        continue;
      // string alpha_ba = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_alpha_ba();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "BroadcastTransformShare.alpha_ba"));
        } else
          goto handle_unusual;
        continue;
      // string b_ab = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_b_ab();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "BroadcastTransformShare.b_ab"));
        } else
          goto handle_unusual;
        continue;
      // string alpha_bb = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_alpha_bb();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "BroadcastTransformShare.alpha_bb"));
        } else
          goto handle_unusual;
        continue;
      // string c_ac = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_c_ac();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "BroadcastTransformShare.c_ac"));
        } else
          goto handle_unusual;
        continue;
      // string alpha_bc = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_alpha_bc();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "BroadcastTransformShare.alpha_bc"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BroadcastTransformShare::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BroadcastTransformShare)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string a_aa = 1;
  if (!this->_internal_a_aa().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_a_aa().data(), static_cast<int>(this->_internal_a_aa().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BroadcastTransformShare.a_aa");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_a_aa(), target);
  }

  // string alpha_ba = 2;
  if (!this->_internal_alpha_ba().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_alpha_ba().data(), static_cast<int>(this->_internal_alpha_ba().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BroadcastTransformShare.alpha_ba");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_alpha_ba(), target);
  }

  // string b_ab = 3;
  if (!this->_internal_b_ab().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_b_ab().data(), static_cast<int>(this->_internal_b_ab().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BroadcastTransformShare.b_ab");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_b_ab(), target);
  }

  // string alpha_bb = 4;
  if (!this->_internal_alpha_bb().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_alpha_bb().data(), static_cast<int>(this->_internal_alpha_bb().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BroadcastTransformShare.alpha_bb");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_alpha_bb(), target);
  }

  // string c_ac = 5;
  if (!this->_internal_c_ac().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_c_ac().data(), static_cast<int>(this->_internal_c_ac().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BroadcastTransformShare.c_ac");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_c_ac(), target);
  }

  // string alpha_bc = 6;
  if (!this->_internal_alpha_bc().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_alpha_bc().data(), static_cast<int>(this->_internal_alpha_bc().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BroadcastTransformShare.alpha_bc");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_alpha_bc(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BroadcastTransformShare)
  return target;
}

size_t BroadcastTransformShare::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BroadcastTransformShare)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string a_aa = 1;
  if (!this->_internal_a_aa().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_a_aa());
  }

  // string alpha_ba = 2;
  if (!this->_internal_alpha_ba().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_alpha_ba());
  }

  // string b_ab = 3;
  if (!this->_internal_b_ab().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_b_ab());
  }

  // string alpha_bb = 4;
  if (!this->_internal_alpha_bb().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_alpha_bb());
  }

  // string c_ac = 5;
  if (!this->_internal_c_ac().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_c_ac());
  }

  // string alpha_bc = 6;
  if (!this->_internal_alpha_bc().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_alpha_bc());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BroadcastTransformShare::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BroadcastTransformShare::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BroadcastTransformShare::GetClassData() const { return &_class_data_; }


void BroadcastTransformShare::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BroadcastTransformShare*>(&to_msg);
  auto& from = static_cast<const BroadcastTransformShare&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BroadcastTransformShare)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_a_aa().empty()) {
    _this->_internal_set_a_aa(from._internal_a_aa());
  }
  if (!from._internal_alpha_ba().empty()) {
    _this->_internal_set_alpha_ba(from._internal_alpha_ba());
  }
  if (!from._internal_b_ab().empty()) {
    _this->_internal_set_b_ab(from._internal_b_ab());
  }
  if (!from._internal_alpha_bb().empty()) {
    _this->_internal_set_alpha_bb(from._internal_alpha_bb());
  }
  if (!from._internal_c_ac().empty()) {
    _this->_internal_set_c_ac(from._internal_c_ac());
  }
  if (!from._internal_alpha_bc().empty()) {
    _this->_internal_set_alpha_bc(from._internal_alpha_bc());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastTransformShare::CopyFrom(const BroadcastTransformShare& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BroadcastTransformShare)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BroadcastTransformShare::IsInitialized() const {
  return true;
}

void BroadcastTransformShare::InternalSwap(BroadcastTransformShare* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.a_aa_, lhs_arena,
      &other->_impl_.a_aa_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.alpha_ba_, lhs_arena,
      &other->_impl_.alpha_ba_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.b_ab_, lhs_arena,
      &other->_impl_.b_ab_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.alpha_bb_, lhs_arena,
      &other->_impl_.alpha_bb_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.c_ac_, lhs_arena,
      &other->_impl_.c_ac_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.alpha_bc_, lhs_arena,
      &other->_impl_.alpha_bc_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata BroadcastTransformShare::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_getter, &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_once,
      file_level_metadata_ptp_5fand_5fbrdcst_5fmsg_2eproto[0]);
}

// ===================================================================

class TransformedShare::_Internal {
 public:
};

TransformedShare::TransformedShare(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TransformedShare)
}
TransformedShare::TransformedShare(const TransformedShare& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransformedShare* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.share_a_){}
    , decltype(_impl_.share_b_){}
    , decltype(_impl_.share_c_){}
    , decltype(_impl_.associated_c_a_){}
    , decltype(_impl_.associated_c_b_){}
    , decltype(_impl_.associated_c_c_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.share_a_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.share_a_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_share_a().empty()) {
    _this->_impl_.share_a_.Set(from._internal_share_a(), 
      _this->GetArenaForAllocation());
  }
  _impl_.share_b_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.share_b_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_share_b().empty()) {
    _this->_impl_.share_b_.Set(from._internal_share_b(), 
      _this->GetArenaForAllocation());
  }
  _impl_.share_c_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.share_c_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_share_c().empty()) {
    _this->_impl_.share_c_.Set(from._internal_share_c(), 
      _this->GetArenaForAllocation());
  }
  _impl_.associated_c_a_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.associated_c_a_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_associated_c_a().empty()) {
    _this->_impl_.associated_c_a_.Set(from._internal_associated_c_a(), 
      _this->GetArenaForAllocation());
  }
  _impl_.associated_c_b_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.associated_c_b_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_associated_c_b().empty()) {
    _this->_impl_.associated_c_b_.Set(from._internal_associated_c_b(), 
      _this->GetArenaForAllocation());
  }
  _impl_.associated_c_c_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.associated_c_c_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_associated_c_c().empty()) {
    _this->_impl_.associated_c_c_.Set(from._internal_associated_c_c(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:TransformedShare)
}

inline void TransformedShare::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.share_a_){}
    , decltype(_impl_.share_b_){}
    , decltype(_impl_.share_c_){}
    , decltype(_impl_.associated_c_a_){}
    , decltype(_impl_.associated_c_b_){}
    , decltype(_impl_.associated_c_c_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.share_a_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.share_a_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.share_b_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.share_b_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.share_c_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.share_c_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.associated_c_a_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.associated_c_a_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.associated_c_b_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.associated_c_b_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.associated_c_c_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.associated_c_c_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TransformedShare::~TransformedShare() {
  // @@protoc_insertion_point(destructor:TransformedShare)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransformedShare::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.share_a_.Destroy();
  _impl_.share_b_.Destroy();
  _impl_.share_c_.Destroy();
  _impl_.associated_c_a_.Destroy();
  _impl_.associated_c_b_.Destroy();
  _impl_.associated_c_c_.Destroy();
}

void TransformedShare::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransformedShare::Clear() {
// @@protoc_insertion_point(message_clear_start:TransformedShare)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.share_a_.ClearToEmpty();
  _impl_.share_b_.ClearToEmpty();
  _impl_.share_c_.ClearToEmpty();
  _impl_.associated_c_a_.ClearToEmpty();
  _impl_.associated_c_b_.ClearToEmpty();
  _impl_.associated_c_c_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransformedShare::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string share_a = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_share_a();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShare.share_a"));
        } else
          goto handle_unusual;
        continue;
      // string share_b = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_share_b();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShare.share_b"));
        } else
          goto handle_unusual;
        continue;
      // string share_c = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_share_c();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShare.share_c"));
        } else
          goto handle_unusual;
        continue;
      // string associated_c_a = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_associated_c_a();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShare.associated_c_a"));
        } else
          goto handle_unusual;
        continue;
      // string associated_c_b = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_associated_c_b();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShare.associated_c_b"));
        } else
          goto handle_unusual;
        continue;
      // string associated_c_c = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_associated_c_c();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShare.associated_c_c"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransformedShare::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TransformedShare)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string share_a = 1;
  if (!this->_internal_share_a().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_share_a().data(), static_cast<int>(this->_internal_share_a().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShare.share_a");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_share_a(), target);
  }

  // string share_b = 2;
  if (!this->_internal_share_b().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_share_b().data(), static_cast<int>(this->_internal_share_b().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShare.share_b");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_share_b(), target);
  }

  // string share_c = 3;
  if (!this->_internal_share_c().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_share_c().data(), static_cast<int>(this->_internal_share_c().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShare.share_c");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_share_c(), target);
  }

  // string associated_c_a = 4;
  if (!this->_internal_associated_c_a().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_associated_c_a().data(), static_cast<int>(this->_internal_associated_c_a().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShare.associated_c_a");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_associated_c_a(), target);
  }

  // string associated_c_b = 5;
  if (!this->_internal_associated_c_b().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_associated_c_b().data(), static_cast<int>(this->_internal_associated_c_b().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShare.associated_c_b");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_associated_c_b(), target);
  }

  // string associated_c_c = 6;
  if (!this->_internal_associated_c_c().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_associated_c_c().data(), static_cast<int>(this->_internal_associated_c_c().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShare.associated_c_c");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_associated_c_c(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TransformedShare)
  return target;
}

size_t TransformedShare::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TransformedShare)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string share_a = 1;
  if (!this->_internal_share_a().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_share_a());
  }

  // string share_b = 2;
  if (!this->_internal_share_b().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_share_b());
  }

  // string share_c = 3;
  if (!this->_internal_share_c().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_share_c());
  }

  // string associated_c_a = 4;
  if (!this->_internal_associated_c_a().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_associated_c_a());
  }

  // string associated_c_b = 5;
  if (!this->_internal_associated_c_b().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_associated_c_b());
  }

  // string associated_c_c = 6;
  if (!this->_internal_associated_c_c().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_associated_c_c());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransformedShare::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransformedShare::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransformedShare::GetClassData() const { return &_class_data_; }


void TransformedShare::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransformedShare*>(&to_msg);
  auto& from = static_cast<const TransformedShare&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TransformedShare)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_share_a().empty()) {
    _this->_internal_set_share_a(from._internal_share_a());
  }
  if (!from._internal_share_b().empty()) {
    _this->_internal_set_share_b(from._internal_share_b());
  }
  if (!from._internal_share_c().empty()) {
    _this->_internal_set_share_c(from._internal_share_c());
  }
  if (!from._internal_associated_c_a().empty()) {
    _this->_internal_set_associated_c_a(from._internal_associated_c_a());
  }
  if (!from._internal_associated_c_b().empty()) {
    _this->_internal_set_associated_c_b(from._internal_associated_c_b());
  }
  if (!from._internal_associated_c_c().empty()) {
    _this->_internal_set_associated_c_c(from._internal_associated_c_c());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransformedShare::CopyFrom(const TransformedShare& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TransformedShare)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransformedShare::IsInitialized() const {
  return true;
}

void TransformedShare::InternalSwap(TransformedShare* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.share_a_, lhs_arena,
      &other->_impl_.share_a_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.share_b_, lhs_arena,
      &other->_impl_.share_b_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.share_c_, lhs_arena,
      &other->_impl_.share_c_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.associated_c_a_, lhs_arena,
      &other->_impl_.associated_c_a_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.associated_c_b_, lhs_arena,
      &other->_impl_.associated_c_b_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.associated_c_c_, lhs_arena,
      &other->_impl_.associated_c_c_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata TransformedShare::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_getter, &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_once,
      file_level_metadata_ptp_5fand_5fbrdcst_5fmsg_2eproto[1]);
}

// ===================================================================

class TransformedShareMsg::_Internal {
 public:
};

TransformedShareMsg::TransformedShareMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TransformedShareMsg)
}
TransformedShareMsg::TransformedShareMsg(const TransformedShareMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransformedShareMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.transformedshare_){from._impl_.transformedshare_}
    , decltype(_impl_.coeff_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.coeff_ = from._impl_.coeff_;
  // @@protoc_insertion_point(copy_constructor:TransformedShareMsg)
}

inline void TransformedShareMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.transformedshare_){arena}
    , decltype(_impl_.coeff_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TransformedShareMsg::~TransformedShareMsg() {
  // @@protoc_insertion_point(destructor:TransformedShareMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransformedShareMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.transformedshare_.~RepeatedPtrField();
}

void TransformedShareMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransformedShareMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:TransformedShareMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.transformedshare_.Clear();
  _impl_.coeff_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransformedShareMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 coeff = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.coeff_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .TransformedShare transformedShare = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_transformedshare(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransformedShareMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TransformedShareMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 coeff = 1;
  if (this->_internal_coeff() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_coeff(), target);
  }

  // repeated .TransformedShare transformedShare = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_transformedshare_size()); i < n; i++) {
    const auto& repfield = this->_internal_transformedshare(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TransformedShareMsg)
  return target;
}

size_t TransformedShareMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TransformedShareMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .TransformedShare transformedShare = 2;
  total_size += 1UL * this->_internal_transformedshare_size();
  for (const auto& msg : this->_impl_.transformedshare_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 coeff = 1;
  if (this->_internal_coeff() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_coeff());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransformedShareMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransformedShareMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransformedShareMsg::GetClassData() const { return &_class_data_; }


void TransformedShareMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransformedShareMsg*>(&to_msg);
  auto& from = static_cast<const TransformedShareMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TransformedShareMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.transformedshare_.MergeFrom(from._impl_.transformedshare_);
  if (from._internal_coeff() != 0) {
    _this->_internal_set_coeff(from._internal_coeff());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransformedShareMsg::CopyFrom(const TransformedShareMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TransformedShareMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransformedShareMsg::IsInitialized() const {
  return true;
}

void TransformedShareMsg::InternalSwap(TransformedShareMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.transformedshare_.InternalSwap(&other->_impl_.transformedshare_);
  swap(_impl_.coeff_, other->_impl_.coeff_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransformedShareMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_getter, &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_once,
      file_level_metadata_ptp_5fand_5fbrdcst_5fmsg_2eproto[2]);
}

// ===================================================================

class BroadcastTransformShareMsg::_Internal {
 public:
};

BroadcastTransformShareMsg::BroadcastTransformShareMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:BroadcastTransformShareMsg)
}
BroadcastTransformShareMsg::BroadcastTransformShareMsg(const BroadcastTransformShareMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BroadcastTransformShareMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.broadcast_){from._impl_.broadcast_}
    , decltype(_impl_.coeff_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.coeff_ = from._impl_.coeff_;
  // @@protoc_insertion_point(copy_constructor:BroadcastTransformShareMsg)
}

inline void BroadcastTransformShareMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.broadcast_){arena}
    , decltype(_impl_.coeff_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BroadcastTransformShareMsg::~BroadcastTransformShareMsg() {
  // @@protoc_insertion_point(destructor:BroadcastTransformShareMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BroadcastTransformShareMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.broadcast_.~RepeatedPtrField();
}

void BroadcastTransformShareMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BroadcastTransformShareMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:BroadcastTransformShareMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.broadcast_.Clear();
  _impl_.coeff_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BroadcastTransformShareMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .BroadcastTransformShare broadcast = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_broadcast(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 coeff = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.coeff_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BroadcastTransformShareMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BroadcastTransformShareMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BroadcastTransformShare broadcast = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_broadcast_size()); i < n; i++) {
    const auto& repfield = this->_internal_broadcast(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int32 coeff = 2;
  if (this->_internal_coeff() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_coeff(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BroadcastTransformShareMsg)
  return target;
}

size_t BroadcastTransformShareMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BroadcastTransformShareMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BroadcastTransformShare broadcast = 1;
  total_size += 1UL * this->_internal_broadcast_size();
  for (const auto& msg : this->_impl_.broadcast_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 coeff = 2;
  if (this->_internal_coeff() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_coeff());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BroadcastTransformShareMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BroadcastTransformShareMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BroadcastTransformShareMsg::GetClassData() const { return &_class_data_; }


void BroadcastTransformShareMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BroadcastTransformShareMsg*>(&to_msg);
  auto& from = static_cast<const BroadcastTransformShareMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BroadcastTransformShareMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.broadcast_.MergeFrom(from._impl_.broadcast_);
  if (from._internal_coeff() != 0) {
    _this->_internal_set_coeff(from._internal_coeff());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastTransformShareMsg::CopyFrom(const BroadcastTransformShareMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BroadcastTransformShareMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BroadcastTransformShareMsg::IsInitialized() const {
  return true;
}

void BroadcastTransformShareMsg::InternalSwap(BroadcastTransformShareMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.broadcast_.InternalSwap(&other->_impl_.broadcast_);
  swap(_impl_.coeff_, other->_impl_.coeff_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BroadcastTransformShareMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_getter, &descriptor_table_ptp_5fand_5fbrdcst_5fmsg_2eproto_once,
      file_level_metadata_ptp_5fand_5fbrdcst_5fmsg_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::BroadcastTransformShare*
Arena::CreateMaybeMessage< ::BroadcastTransformShare >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BroadcastTransformShare >(arena);
}
template<> PROTOBUF_NOINLINE ::TransformedShare*
Arena::CreateMaybeMessage< ::TransformedShare >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TransformedShare >(arena);
}
template<> PROTOBUF_NOINLINE ::TransformedShareMsg*
Arena::CreateMaybeMessage< ::TransformedShareMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TransformedShareMsg >(arena);
}
template<> PROTOBUF_NOINLINE ::BroadcastTransformShareMsg*
Arena::CreateMaybeMessage< ::BroadcastTransformShareMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BroadcastTransformShareMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
