// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: randVal_msg.proto

#include "randVal_msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR BroadcastTransformShareRndVal::BroadcastTransformShareRndVal(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.r_ar_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.alpha_br_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BroadcastTransformShareRndValDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastTransformShareRndValDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastTransformShareRndValDefaultTypeInternal() {}
  union {
    BroadcastTransformShareRndVal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastTransformShareRndValDefaultTypeInternal _BroadcastTransformShareRndVal_default_instance_;
PROTOBUF_CONSTEXPR TransformedShareRndVal::TransformedShareRndVal(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.share_r_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.associated_c_r_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.lsss_share_r_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}} {}
struct TransformedShareRndValDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransformedShareRndValDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransformedShareRndValDefaultTypeInternal() {}
  union {
    TransformedShareRndVal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransformedShareRndValDefaultTypeInternal _TransformedShareRndVal_default_instance_;
PROTOBUF_CONSTEXPR TransformedShareMsgRndVal::TransformedShareMsgRndVal(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.transformedshare_)*/{}
  , /*decltype(_impl_.coeff_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TransformedShareMsgRndValDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TransformedShareMsgRndValDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TransformedShareMsgRndValDefaultTypeInternal() {}
  union {
    TransformedShareMsgRndVal _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TransformedShareMsgRndValDefaultTypeInternal _TransformedShareMsgRndVal_default_instance_;
PROTOBUF_CONSTEXPR BroadcastTransformShareRndValMsg::BroadcastTransformShareRndValMsg(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.broadcast_)*/{}
  , /*decltype(_impl_.coeff_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BroadcastTransformShareRndValMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastTransformShareRndValMsgDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastTransformShareRndValMsgDefaultTypeInternal() {}
  union {
    BroadcastTransformShareRndValMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastTransformShareRndValMsgDefaultTypeInternal _BroadcastTransformShareRndValMsg_default_instance_;
static ::_pb::Metadata file_level_metadata_randVal_5fmsg_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_randVal_5fmsg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_randVal_5fmsg_2eproto = nullptr;

const uint32_t TableStruct_randVal_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareRndVal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareRndVal, _impl_.r_ar_),
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareRndVal, _impl_.alpha_br_),
  PROTOBUF_FIELD_OFFSET(::TransformedShareRndVal, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::TransformedShareRndVal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TransformedShareRndVal, _impl_.share_r_),
  PROTOBUF_FIELD_OFFSET(::TransformedShareRndVal, _impl_.associated_c_r_),
  PROTOBUF_FIELD_OFFSET(::TransformedShareRndVal, _impl_.lsss_share_r_),
  ~0u,
  ~0u,
  0,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TransformedShareMsgRndVal, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::TransformedShareMsgRndVal, _impl_.coeff_),
  PROTOBUF_FIELD_OFFSET(::TransformedShareMsgRndVal, _impl_.transformedshare_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareRndValMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareRndValMsg, _impl_.broadcast_),
  PROTOBUF_FIELD_OFFSET(::BroadcastTransformShareRndValMsg, _impl_.coeff_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::BroadcastTransformShareRndVal)},
  { 8, 17, -1, sizeof(::TransformedShareRndVal)},
  { 20, -1, -1, sizeof(::TransformedShareMsgRndVal)},
  { 28, -1, -1, sizeof(::BroadcastTransformShareRndValMsg)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_BroadcastTransformShareRndVal_default_instance_._instance,
  &::_TransformedShareRndVal_default_instance_._instance,
  &::_TransformedShareMsgRndVal_default_instance_._instance,
  &::_BroadcastTransformShareRndValMsg_default_instance_._instance,
};

const char descriptor_table_protodef_randVal_5fmsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021randVal_msg.proto\"\?\n\035BroadcastTransfor"
  "mShareRndVal\022\014\n\004r_ar\030\001 \001(\t\022\020\n\010alpha_br\030\002"
  " \001(\t\"m\n\026TransformedShareRndVal\022\017\n\007share_"
  "r\030\001 \001(\t\022\026\n\016associated_c_r\030\002 \001(\t\022\031\n\014lsss_"
  "share_r\030\003 \001(\tH\000\210\001\001B\017\n\r_lsss_share_r\"]\n\031T"
  "ransformedShareMsgRndVal\022\r\n\005coeff\030\001 \001(\005\022"
  "1\n\020transformedShare\030\002 \003(\0132\027.TransformedS"
  "hareRndVal\"d\n BroadcastTransformShareRnd"
  "ValMsg\0221\n\tbroadcast\030\001 \003(\0132\036.BroadcastTra"
  "nsformShareRndVal\022\r\n\005coeff\030\002 \001(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_randVal_5fmsg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_randVal_5fmsg_2eproto = {
    false, false, 400, descriptor_table_protodef_randVal_5fmsg_2eproto,
    "randVal_msg.proto",
    &descriptor_table_randVal_5fmsg_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_randVal_5fmsg_2eproto::offsets,
    file_level_metadata_randVal_5fmsg_2eproto, file_level_enum_descriptors_randVal_5fmsg_2eproto,
    file_level_service_descriptors_randVal_5fmsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_randVal_5fmsg_2eproto_getter() {
  return &descriptor_table_randVal_5fmsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_randVal_5fmsg_2eproto(&descriptor_table_randVal_5fmsg_2eproto);

// ===================================================================

class BroadcastTransformShareRndVal::_Internal {
 public:
};

BroadcastTransformShareRndVal::BroadcastTransformShareRndVal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:BroadcastTransformShareRndVal)
}
BroadcastTransformShareRndVal::BroadcastTransformShareRndVal(const BroadcastTransformShareRndVal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BroadcastTransformShareRndVal* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.r_ar_){}
    , decltype(_impl_.alpha_br_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.r_ar_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.r_ar_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_r_ar().empty()) {
    _this->_impl_.r_ar_.Set(from._internal_r_ar(), 
      _this->GetArenaForAllocation());
  }
  _impl_.alpha_br_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alpha_br_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_alpha_br().empty()) {
    _this->_impl_.alpha_br_.Set(from._internal_alpha_br(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:BroadcastTransformShareRndVal)
}

inline void BroadcastTransformShareRndVal::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.r_ar_){}
    , decltype(_impl_.alpha_br_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.r_ar_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.r_ar_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.alpha_br_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.alpha_br_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BroadcastTransformShareRndVal::~BroadcastTransformShareRndVal() {
  // @@protoc_insertion_point(destructor:BroadcastTransformShareRndVal)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BroadcastTransformShareRndVal::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.r_ar_.Destroy();
  _impl_.alpha_br_.Destroy();
}

void BroadcastTransformShareRndVal::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BroadcastTransformShareRndVal::Clear() {
// @@protoc_insertion_point(message_clear_start:BroadcastTransformShareRndVal)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.r_ar_.ClearToEmpty();
  _impl_.alpha_br_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BroadcastTransformShareRndVal::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string r_ar = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_r_ar();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "BroadcastTransformShareRndVal.r_ar"));
        } else
          goto handle_unusual;
        continue;
      // string alpha_br = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_alpha_br();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "BroadcastTransformShareRndVal.alpha_br"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BroadcastTransformShareRndVal::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BroadcastTransformShareRndVal)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string r_ar = 1;
  if (!this->_internal_r_ar().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_r_ar().data(), static_cast<int>(this->_internal_r_ar().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BroadcastTransformShareRndVal.r_ar");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_r_ar(), target);
  }

  // string alpha_br = 2;
  if (!this->_internal_alpha_br().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_alpha_br().data(), static_cast<int>(this->_internal_alpha_br().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "BroadcastTransformShareRndVal.alpha_br");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_alpha_br(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BroadcastTransformShareRndVal)
  return target;
}

size_t BroadcastTransformShareRndVal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BroadcastTransformShareRndVal)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string r_ar = 1;
  if (!this->_internal_r_ar().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_r_ar());
  }

  // string alpha_br = 2;
  if (!this->_internal_alpha_br().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_alpha_br());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BroadcastTransformShareRndVal::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BroadcastTransformShareRndVal::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BroadcastTransformShareRndVal::GetClassData() const { return &_class_data_; }


void BroadcastTransformShareRndVal::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BroadcastTransformShareRndVal*>(&to_msg);
  auto& from = static_cast<const BroadcastTransformShareRndVal&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BroadcastTransformShareRndVal)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_r_ar().empty()) {
    _this->_internal_set_r_ar(from._internal_r_ar());
  }
  if (!from._internal_alpha_br().empty()) {
    _this->_internal_set_alpha_br(from._internal_alpha_br());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastTransformShareRndVal::CopyFrom(const BroadcastTransformShareRndVal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BroadcastTransformShareRndVal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BroadcastTransformShareRndVal::IsInitialized() const {
  return true;
}

void BroadcastTransformShareRndVal::InternalSwap(BroadcastTransformShareRndVal* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.r_ar_, lhs_arena,
      &other->_impl_.r_ar_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.alpha_br_, lhs_arena,
      &other->_impl_.alpha_br_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata BroadcastTransformShareRndVal::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_randVal_5fmsg_2eproto_getter, &descriptor_table_randVal_5fmsg_2eproto_once,
      file_level_metadata_randVal_5fmsg_2eproto[0]);
}

// ===================================================================

class TransformedShareRndVal::_Internal {
 public:
  using HasBits = decltype(std::declval<TransformedShareRndVal>()._impl_._has_bits_);
  static void set_has_lsss_share_r(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

TransformedShareRndVal::TransformedShareRndVal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TransformedShareRndVal)
}
TransformedShareRndVal::TransformedShareRndVal(const TransformedShareRndVal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransformedShareRndVal* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.share_r_){}
    , decltype(_impl_.associated_c_r_){}
    , decltype(_impl_.lsss_share_r_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.share_r_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.share_r_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_share_r().empty()) {
    _this->_impl_.share_r_.Set(from._internal_share_r(), 
      _this->GetArenaForAllocation());
  }
  _impl_.associated_c_r_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.associated_c_r_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_associated_c_r().empty()) {
    _this->_impl_.associated_c_r_.Set(from._internal_associated_c_r(), 
      _this->GetArenaForAllocation());
  }
  _impl_.lsss_share_r_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lsss_share_r_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_lsss_share_r()) {
    _this->_impl_.lsss_share_r_.Set(from._internal_lsss_share_r(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:TransformedShareRndVal)
}

inline void TransformedShareRndVal::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.share_r_){}
    , decltype(_impl_.associated_c_r_){}
    , decltype(_impl_.lsss_share_r_){}
  };
  _impl_.share_r_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.share_r_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.associated_c_r_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.associated_c_r_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.lsss_share_r_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.lsss_share_r_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TransformedShareRndVal::~TransformedShareRndVal() {
  // @@protoc_insertion_point(destructor:TransformedShareRndVal)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransformedShareRndVal::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.share_r_.Destroy();
  _impl_.associated_c_r_.Destroy();
  _impl_.lsss_share_r_.Destroy();
}

void TransformedShareRndVal::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransformedShareRndVal::Clear() {
// @@protoc_insertion_point(message_clear_start:TransformedShareRndVal)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.share_r_.ClearToEmpty();
  _impl_.associated_c_r_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.lsss_share_r_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransformedShareRndVal::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string share_r = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_share_r();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShareRndVal.share_r"));
        } else
          goto handle_unusual;
        continue;
      // string associated_c_r = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_associated_c_r();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShareRndVal.associated_c_r"));
        } else
          goto handle_unusual;
        continue;
      // optional string lsss_share_r = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_lsss_share_r();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "TransformedShareRndVal.lsss_share_r"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransformedShareRndVal::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TransformedShareRndVal)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string share_r = 1;
  if (!this->_internal_share_r().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_share_r().data(), static_cast<int>(this->_internal_share_r().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShareRndVal.share_r");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_share_r(), target);
  }

  // string associated_c_r = 2;
  if (!this->_internal_associated_c_r().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_associated_c_r().data(), static_cast<int>(this->_internal_associated_c_r().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShareRndVal.associated_c_r");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_associated_c_r(), target);
  }

  // optional string lsss_share_r = 3;
  if (_internal_has_lsss_share_r()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lsss_share_r().data(), static_cast<int>(this->_internal_lsss_share_r().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TransformedShareRndVal.lsss_share_r");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_lsss_share_r(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TransformedShareRndVal)
  return target;
}

size_t TransformedShareRndVal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TransformedShareRndVal)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string share_r = 1;
  if (!this->_internal_share_r().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_share_r());
  }

  // string associated_c_r = 2;
  if (!this->_internal_associated_c_r().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_associated_c_r());
  }

  // optional string lsss_share_r = 3;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lsss_share_r());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransformedShareRndVal::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransformedShareRndVal::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransformedShareRndVal::GetClassData() const { return &_class_data_; }


void TransformedShareRndVal::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransformedShareRndVal*>(&to_msg);
  auto& from = static_cast<const TransformedShareRndVal&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TransformedShareRndVal)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_share_r().empty()) {
    _this->_internal_set_share_r(from._internal_share_r());
  }
  if (!from._internal_associated_c_r().empty()) {
    _this->_internal_set_associated_c_r(from._internal_associated_c_r());
  }
  if (from._internal_has_lsss_share_r()) {
    _this->_internal_set_lsss_share_r(from._internal_lsss_share_r());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransformedShareRndVal::CopyFrom(const TransformedShareRndVal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TransformedShareRndVal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransformedShareRndVal::IsInitialized() const {
  return true;
}

void TransformedShareRndVal::InternalSwap(TransformedShareRndVal* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.share_r_, lhs_arena,
      &other->_impl_.share_r_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.associated_c_r_, lhs_arena,
      &other->_impl_.associated_c_r_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.lsss_share_r_, lhs_arena,
      &other->_impl_.lsss_share_r_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata TransformedShareRndVal::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_randVal_5fmsg_2eproto_getter, &descriptor_table_randVal_5fmsg_2eproto_once,
      file_level_metadata_randVal_5fmsg_2eproto[1]);
}

// ===================================================================

class TransformedShareMsgRndVal::_Internal {
 public:
};

TransformedShareMsgRndVal::TransformedShareMsgRndVal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:TransformedShareMsgRndVal)
}
TransformedShareMsgRndVal::TransformedShareMsgRndVal(const TransformedShareMsgRndVal& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TransformedShareMsgRndVal* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.transformedshare_){from._impl_.transformedshare_}
    , decltype(_impl_.coeff_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.coeff_ = from._impl_.coeff_;
  // @@protoc_insertion_point(copy_constructor:TransformedShareMsgRndVal)
}

inline void TransformedShareMsgRndVal::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.transformedshare_){arena}
    , decltype(_impl_.coeff_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TransformedShareMsgRndVal::~TransformedShareMsgRndVal() {
  // @@protoc_insertion_point(destructor:TransformedShareMsgRndVal)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TransformedShareMsgRndVal::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.transformedshare_.~RepeatedPtrField();
}

void TransformedShareMsgRndVal::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TransformedShareMsgRndVal::Clear() {
// @@protoc_insertion_point(message_clear_start:TransformedShareMsgRndVal)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.transformedshare_.Clear();
  _impl_.coeff_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TransformedShareMsgRndVal::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 coeff = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.coeff_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .TransformedShareRndVal transformedShare = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_transformedshare(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TransformedShareMsgRndVal::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TransformedShareMsgRndVal)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 coeff = 1;
  if (this->_internal_coeff() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_coeff(), target);
  }

  // repeated .TransformedShareRndVal transformedShare = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_transformedshare_size()); i < n; i++) {
    const auto& repfield = this->_internal_transformedshare(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TransformedShareMsgRndVal)
  return target;
}

size_t TransformedShareMsgRndVal::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TransformedShareMsgRndVal)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .TransformedShareRndVal transformedShare = 2;
  total_size += 1UL * this->_internal_transformedshare_size();
  for (const auto& msg : this->_impl_.transformedshare_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 coeff = 1;
  if (this->_internal_coeff() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_coeff());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TransformedShareMsgRndVal::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TransformedShareMsgRndVal::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TransformedShareMsgRndVal::GetClassData() const { return &_class_data_; }


void TransformedShareMsgRndVal::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TransformedShareMsgRndVal*>(&to_msg);
  auto& from = static_cast<const TransformedShareMsgRndVal&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TransformedShareMsgRndVal)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.transformedshare_.MergeFrom(from._impl_.transformedshare_);
  if (from._internal_coeff() != 0) {
    _this->_internal_set_coeff(from._internal_coeff());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TransformedShareMsgRndVal::CopyFrom(const TransformedShareMsgRndVal& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TransformedShareMsgRndVal)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TransformedShareMsgRndVal::IsInitialized() const {
  return true;
}

void TransformedShareMsgRndVal::InternalSwap(TransformedShareMsgRndVal* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.transformedshare_.InternalSwap(&other->_impl_.transformedshare_);
  swap(_impl_.coeff_, other->_impl_.coeff_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TransformedShareMsgRndVal::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_randVal_5fmsg_2eproto_getter, &descriptor_table_randVal_5fmsg_2eproto_once,
      file_level_metadata_randVal_5fmsg_2eproto[2]);
}

// ===================================================================

class BroadcastTransformShareRndValMsg::_Internal {
 public:
};

BroadcastTransformShareRndValMsg::BroadcastTransformShareRndValMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:BroadcastTransformShareRndValMsg)
}
BroadcastTransformShareRndValMsg::BroadcastTransformShareRndValMsg(const BroadcastTransformShareRndValMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BroadcastTransformShareRndValMsg* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.broadcast_){from._impl_.broadcast_}
    , decltype(_impl_.coeff_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.coeff_ = from._impl_.coeff_;
  // @@protoc_insertion_point(copy_constructor:BroadcastTransformShareRndValMsg)
}

inline void BroadcastTransformShareRndValMsg::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.broadcast_){arena}
    , decltype(_impl_.coeff_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BroadcastTransformShareRndValMsg::~BroadcastTransformShareRndValMsg() {
  // @@protoc_insertion_point(destructor:BroadcastTransformShareRndValMsg)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BroadcastTransformShareRndValMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.broadcast_.~RepeatedPtrField();
}

void BroadcastTransformShareRndValMsg::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BroadcastTransformShareRndValMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:BroadcastTransformShareRndValMsg)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.broadcast_.Clear();
  _impl_.coeff_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BroadcastTransformShareRndValMsg::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .BroadcastTransformShareRndVal broadcast = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_broadcast(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 coeff = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.coeff_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BroadcastTransformShareRndValMsg::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BroadcastTransformShareRndValMsg)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BroadcastTransformShareRndVal broadcast = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_broadcast_size()); i < n; i++) {
    const auto& repfield = this->_internal_broadcast(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int32 coeff = 2;
  if (this->_internal_coeff() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_coeff(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BroadcastTransformShareRndValMsg)
  return target;
}

size_t BroadcastTransformShareRndValMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BroadcastTransformShareRndValMsg)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .BroadcastTransformShareRndVal broadcast = 1;
  total_size += 1UL * this->_internal_broadcast_size();
  for (const auto& msg : this->_impl_.broadcast_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // int32 coeff = 2;
  if (this->_internal_coeff() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_coeff());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BroadcastTransformShareRndValMsg::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BroadcastTransformShareRndValMsg::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BroadcastTransformShareRndValMsg::GetClassData() const { return &_class_data_; }


void BroadcastTransformShareRndValMsg::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BroadcastTransformShareRndValMsg*>(&to_msg);
  auto& from = static_cast<const BroadcastTransformShareRndValMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BroadcastTransformShareRndValMsg)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.broadcast_.MergeFrom(from._impl_.broadcast_);
  if (from._internal_coeff() != 0) {
    _this->_internal_set_coeff(from._internal_coeff());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastTransformShareRndValMsg::CopyFrom(const BroadcastTransformShareRndValMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BroadcastTransformShareRndValMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BroadcastTransformShareRndValMsg::IsInitialized() const {
  return true;
}

void BroadcastTransformShareRndValMsg::InternalSwap(BroadcastTransformShareRndValMsg* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.broadcast_.InternalSwap(&other->_impl_.broadcast_);
  swap(_impl_.coeff_, other->_impl_.coeff_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BroadcastTransformShareRndValMsg::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_randVal_5fmsg_2eproto_getter, &descriptor_table_randVal_5fmsg_2eproto_once,
      file_level_metadata_randVal_5fmsg_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::BroadcastTransformShareRndVal*
Arena::CreateMaybeMessage< ::BroadcastTransformShareRndVal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BroadcastTransformShareRndVal >(arena);
}
template<> PROTOBUF_NOINLINE ::TransformedShareRndVal*
Arena::CreateMaybeMessage< ::TransformedShareRndVal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TransformedShareRndVal >(arena);
}
template<> PROTOBUF_NOINLINE ::TransformedShareMsgRndVal*
Arena::CreateMaybeMessage< ::TransformedShareMsgRndVal >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TransformedShareMsgRndVal >(arena);
}
template<> PROTOBUF_NOINLINE ::BroadcastTransformShareRndValMsg*
Arena::CreateMaybeMessage< ::BroadcastTransformShareRndValMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::BroadcastTransformShareRndValMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
